/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockTimeService.h"

static const char* CMockString_TimeService_destroy = "TimeService_destroy";
static const char* CMockString_TimeService_getTime = "TimeService_getTime";
static const char* CMockString_TimeService_init = "TimeService_init";
static const char* CMockString_TimeService_startPeriodicAlarm = "TimeService_startPeriodicAlarm";
static const char* CMockString_TimeService_stopPeriodicAlarm = "TimeService_stopPeriodicAlarm";
static const char* CMockString_callback = "callback";
static const char* CMockString_handle = "handle";
static const char* CMockString_seconds = "seconds";
static const char* CMockString_time = "time";

typedef struct _CMOCK_TimeService_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_TimeService_init_CALL_INSTANCE;

typedef struct _CMOCK_TimeService_destroy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_TimeService_destroy_CALL_INSTANCE;

typedef struct _CMOCK_TimeService_getTime_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  Time* Expected_time;
  char ReturnThruPtr_time_Used;
  Time const* ReturnThruPtr_time_Val;
  size_t ReturnThruPtr_time_Size;
  char IgnoreArg_time;

} CMOCK_TimeService_getTime_CALL_INSTANCE;

typedef struct _CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  int Expected_seconds;
  cmock_TimeService_func_ptr1 Expected_callback;
  char IgnoreArg_seconds;
  char IgnoreArg_callback;

} CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE;

typedef struct _CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int Expected_handle;
  char IgnoreArg_handle;

} CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE;

static struct MockTimeServiceInstance
{
  char TimeService_init_IgnoreBool;
  char TimeService_init_CallbackBool;
  CMOCK_TimeService_init_CALLBACK TimeService_init_CallbackFunctionPointer;
  int TimeService_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TimeService_init_CallInstance;
  char TimeService_destroy_IgnoreBool;
  char TimeService_destroy_CallbackBool;
  CMOCK_TimeService_destroy_CALLBACK TimeService_destroy_CallbackFunctionPointer;
  int TimeService_destroy_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TimeService_destroy_CallInstance;
  char TimeService_getTime_IgnoreBool;
  char TimeService_getTime_CallbackBool;
  CMOCK_TimeService_getTime_CALLBACK TimeService_getTime_CallbackFunctionPointer;
  int TimeService_getTime_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TimeService_getTime_CallInstance;
  char TimeService_startPeriodicAlarm_IgnoreBool;
  int TimeService_startPeriodicAlarm_FinalReturn;
  char TimeService_startPeriodicAlarm_CallbackBool;
  CMOCK_TimeService_startPeriodicAlarm_CALLBACK TimeService_startPeriodicAlarm_CallbackFunctionPointer;
  int TimeService_startPeriodicAlarm_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TimeService_startPeriodicAlarm_CallInstance;
  char TimeService_stopPeriodicAlarm_IgnoreBool;
  char TimeService_stopPeriodicAlarm_CallbackBool;
  CMOCK_TimeService_stopPeriodicAlarm_CALLBACK TimeService_stopPeriodicAlarm_CallbackFunctionPointer;
  int TimeService_stopPeriodicAlarm_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TimeService_stopPeriodicAlarm_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockTimeService_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.TimeService_init_CallInstance;
  if (Mock.TimeService_init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TimeService_init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TimeService_init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.TimeService_destroy_CallInstance;
  if (Mock.TimeService_destroy_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TimeService_destroy);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TimeService_destroy_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.TimeService_getTime_CallInstance;
  if (Mock.TimeService_getTime_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TimeService_getTime);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TimeService_getTime_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.TimeService_startPeriodicAlarm_CallInstance;
  if (Mock.TimeService_startPeriodicAlarm_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TimeService_startPeriodicAlarm);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TimeService_startPeriodicAlarm_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.TimeService_stopPeriodicAlarm_CallInstance;
  if (Mock.TimeService_stopPeriodicAlarm_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TimeService_stopPeriodicAlarm);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TimeService_stopPeriodicAlarm_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void MockTimeService_Init(void)
{
  MockTimeService_Destroy();
}

void MockTimeService_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void TimeService_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TimeService_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TimeService_init);
  cmock_call_instance = (CMOCK_TimeService_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TimeService_init_CallInstance);
  Mock.TimeService_init_CallInstance = CMock_Guts_MemNext(Mock.TimeService_init_CallInstance);
  if (Mock.TimeService_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.TimeService_init_CallbackBool &&
      Mock.TimeService_init_CallbackFunctionPointer != NULL)
  {
    Mock.TimeService_init_CallbackFunctionPointer(Mock.TimeService_init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.TimeService_init_CallbackFunctionPointer != NULL)
  {
    Mock.TimeService_init_CallbackFunctionPointer(Mock.TimeService_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void TimeService_init_CMockIgnore(void)
{
  Mock.TimeService_init_IgnoreBool = (char)1;
}

void TimeService_init_CMockStopIgnore(void)
{
  Mock.TimeService_init_IgnoreBool = (char)0;
}

void TimeService_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimeService_init_CALL_INSTANCE));
  CMOCK_TimeService_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TimeService_init_CallInstance = CMock_Guts_MemChain(Mock.TimeService_init_CallInstance, cmock_guts_index);
  Mock.TimeService_init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void TimeService_init_AddCallback(CMOCK_TimeService_init_CALLBACK Callback)
{
  Mock.TimeService_init_IgnoreBool = (char)0;
  Mock.TimeService_init_CallbackBool = (char)1;
  Mock.TimeService_init_CallbackFunctionPointer = Callback;
}

void TimeService_init_Stub(CMOCK_TimeService_init_CALLBACK Callback)
{
  Mock.TimeService_init_IgnoreBool = (char)0;
  Mock.TimeService_init_CallbackBool = (char)0;
  Mock.TimeService_init_CallbackFunctionPointer = Callback;
}

void TimeService_destroy(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TimeService_destroy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TimeService_destroy);
  cmock_call_instance = (CMOCK_TimeService_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TimeService_destroy_CallInstance);
  Mock.TimeService_destroy_CallInstance = CMock_Guts_MemNext(Mock.TimeService_destroy_CallInstance);
  if (Mock.TimeService_destroy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.TimeService_destroy_CallbackBool &&
      Mock.TimeService_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.TimeService_destroy_CallbackFunctionPointer(Mock.TimeService_destroy_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.TimeService_destroy_CallbackFunctionPointer != NULL)
  {
    Mock.TimeService_destroy_CallbackFunctionPointer(Mock.TimeService_destroy_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void TimeService_destroy_CMockIgnore(void)
{
  Mock.TimeService_destroy_IgnoreBool = (char)1;
}

void TimeService_destroy_CMockStopIgnore(void)
{
  Mock.TimeService_destroy_IgnoreBool = (char)0;
}

void TimeService_destroy_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimeService_destroy_CALL_INSTANCE));
  CMOCK_TimeService_destroy_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_destroy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TimeService_destroy_CallInstance = CMock_Guts_MemChain(Mock.TimeService_destroy_CallInstance, cmock_guts_index);
  Mock.TimeService_destroy_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void TimeService_destroy_AddCallback(CMOCK_TimeService_destroy_CALLBACK Callback)
{
  Mock.TimeService_destroy_IgnoreBool = (char)0;
  Mock.TimeService_destroy_CallbackBool = (char)1;
  Mock.TimeService_destroy_CallbackFunctionPointer = Callback;
}

void TimeService_destroy_Stub(CMOCK_TimeService_destroy_CALLBACK Callback)
{
  Mock.TimeService_destroy_IgnoreBool = (char)0;
  Mock.TimeService_destroy_CallbackBool = (char)0;
  Mock.TimeService_destroy_CallbackFunctionPointer = Callback;
}

void TimeService_getTime(Time* time)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TimeService_getTime_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TimeService_getTime);
  cmock_call_instance = (CMOCK_TimeService_getTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TimeService_getTime_CallInstance);
  Mock.TimeService_getTime_CallInstance = CMock_Guts_MemNext(Mock.TimeService_getTime_CallInstance);
  if (Mock.TimeService_getTime_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.TimeService_getTime_CallbackBool &&
      Mock.TimeService_getTime_CallbackFunctionPointer != NULL)
  {
    Mock.TimeService_getTime_CallbackFunctionPointer(time, Mock.TimeService_getTime_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_time)
  {
    UNITY_SET_DETAILS(CMockString_TimeService_getTime,CMockString_time);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_time), (void*)(time), sizeof(Time), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.TimeService_getTime_CallbackFunctionPointer != NULL)
  {
    Mock.TimeService_getTime_CallbackFunctionPointer(time, Mock.TimeService_getTime_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_time_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(time, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)time, (const void*)cmock_call_instance->ReturnThruPtr_time_Val,
      cmock_call_instance->ReturnThruPtr_time_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_TimeService_getTime(CMOCK_TimeService_getTime_CALL_INSTANCE* cmock_call_instance, Time* time);
void CMockExpectParameters_TimeService_getTime(CMOCK_TimeService_getTime_CALL_INSTANCE* cmock_call_instance, Time* time)
{
  cmock_call_instance->Expected_time = time;
  cmock_call_instance->IgnoreArg_time = 0;
  cmock_call_instance->ReturnThruPtr_time_Used = 0;
}

void TimeService_getTime_CMockIgnore(void)
{
  Mock.TimeService_getTime_IgnoreBool = (char)1;
}

void TimeService_getTime_CMockStopIgnore(void)
{
  Mock.TimeService_getTime_IgnoreBool = (char)0;
}

void TimeService_getTime_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimeService_getTime_CALL_INSTANCE));
  CMOCK_TimeService_getTime_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_getTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TimeService_getTime_CallInstance = CMock_Guts_MemChain(Mock.TimeService_getTime_CallInstance, cmock_guts_index);
  Mock.TimeService_getTime_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void TimeService_getTime_CMockExpect(UNITY_LINE_TYPE cmock_line, Time* time)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimeService_getTime_CALL_INSTANCE));
  CMOCK_TimeService_getTime_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_getTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TimeService_getTime_CallInstance = CMock_Guts_MemChain(Mock.TimeService_getTime_CallInstance, cmock_guts_index);
  Mock.TimeService_getTime_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_TimeService_getTime(cmock_call_instance, time);
}

void TimeService_getTime_AddCallback(CMOCK_TimeService_getTime_CALLBACK Callback)
{
  Mock.TimeService_getTime_IgnoreBool = (char)0;
  Mock.TimeService_getTime_CallbackBool = (char)1;
  Mock.TimeService_getTime_CallbackFunctionPointer = Callback;
}

void TimeService_getTime_Stub(CMOCK_TimeService_getTime_CALLBACK Callback)
{
  Mock.TimeService_getTime_IgnoreBool = (char)0;
  Mock.TimeService_getTime_CallbackBool = (char)0;
  Mock.TimeService_getTime_CallbackFunctionPointer = Callback;
}

void TimeService_getTime_CMockReturnMemThruPtr_time(UNITY_LINE_TYPE cmock_line, Time const* time, size_t cmock_size)
{
  CMOCK_TimeService_getTime_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_getTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TimeService_getTime_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_time_Used = 1;
  cmock_call_instance->ReturnThruPtr_time_Val = time;
  cmock_call_instance->ReturnThruPtr_time_Size = cmock_size;
}

void TimeService_getTime_CMockIgnoreArg_time(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TimeService_getTime_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_getTime_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TimeService_getTime_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_time = 1;
}

int TimeService_startPeriodicAlarm(int seconds, cmock_TimeService_func_ptr1 callback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TimeService_startPeriodicAlarm);
  cmock_call_instance = (CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TimeService_startPeriodicAlarm_CallInstance);
  Mock.TimeService_startPeriodicAlarm_CallInstance = CMock_Guts_MemNext(Mock.TimeService_startPeriodicAlarm_CallInstance);
  if (Mock.TimeService_startPeriodicAlarm_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.TimeService_startPeriodicAlarm_FinalReturn;
    Mock.TimeService_startPeriodicAlarm_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.TimeService_startPeriodicAlarm_CallbackBool &&
      Mock.TimeService_startPeriodicAlarm_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.TimeService_startPeriodicAlarm_CallbackFunctionPointer(seconds, callback, Mock.TimeService_startPeriodicAlarm_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_seconds)
  {
    UNITY_SET_DETAILS(CMockString_TimeService_startPeriodicAlarm,CMockString_seconds);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_seconds, seconds, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_callback)
  {
    UNITY_SET_DETAILS(CMockString_TimeService_startPeriodicAlarm,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_callback, callback, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.TimeService_startPeriodicAlarm_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.TimeService_startPeriodicAlarm_CallbackFunctionPointer(seconds, callback, Mock.TimeService_startPeriodicAlarm_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_TimeService_startPeriodicAlarm(CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE* cmock_call_instance, int seconds, cmock_TimeService_func_ptr1 callback);
void CMockExpectParameters_TimeService_startPeriodicAlarm(CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE* cmock_call_instance, int seconds, cmock_TimeService_func_ptr1 callback)
{
  cmock_call_instance->Expected_seconds = seconds;
  cmock_call_instance->IgnoreArg_seconds = 0;
  memcpy((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback),
         sizeof(cmock_TimeService_func_ptr1[sizeof(callback) == sizeof(cmock_TimeService_func_ptr1) ? 1 : -1])); /* add cmock_TimeService_func_ptr1 to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_callback = 0;
}

void TimeService_startPeriodicAlarm_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE));
  CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TimeService_startPeriodicAlarm_CallInstance = CMock_Guts_MemChain(Mock.TimeService_startPeriodicAlarm_CallInstance, cmock_guts_index);
  Mock.TimeService_startPeriodicAlarm_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.TimeService_startPeriodicAlarm_IgnoreBool = (char)1;
}

void TimeService_startPeriodicAlarm_CMockStopIgnore(void)
{
  if(Mock.TimeService_startPeriodicAlarm_IgnoreBool)
    Mock.TimeService_startPeriodicAlarm_CallInstance = CMock_Guts_MemNext(Mock.TimeService_startPeriodicAlarm_CallInstance);
  Mock.TimeService_startPeriodicAlarm_IgnoreBool = (char)0;
}

void TimeService_startPeriodicAlarm_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE));
  CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TimeService_startPeriodicAlarm_CallInstance = CMock_Guts_MemChain(Mock.TimeService_startPeriodicAlarm_CallInstance, cmock_guts_index);
  Mock.TimeService_startPeriodicAlarm_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void TimeService_startPeriodicAlarm_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int seconds, cmock_TimeService_func_ptr1 callback, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE));
  CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TimeService_startPeriodicAlarm_CallInstance = CMock_Guts_MemChain(Mock.TimeService_startPeriodicAlarm_CallInstance, cmock_guts_index);
  Mock.TimeService_startPeriodicAlarm_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_TimeService_startPeriodicAlarm(cmock_call_instance, seconds, callback);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void TimeService_startPeriodicAlarm_AddCallback(CMOCK_TimeService_startPeriodicAlarm_CALLBACK Callback)
{
  Mock.TimeService_startPeriodicAlarm_IgnoreBool = (char)0;
  Mock.TimeService_startPeriodicAlarm_CallbackBool = (char)1;
  Mock.TimeService_startPeriodicAlarm_CallbackFunctionPointer = Callback;
}

void TimeService_startPeriodicAlarm_Stub(CMOCK_TimeService_startPeriodicAlarm_CALLBACK Callback)
{
  Mock.TimeService_startPeriodicAlarm_IgnoreBool = (char)0;
  Mock.TimeService_startPeriodicAlarm_CallbackBool = (char)0;
  Mock.TimeService_startPeriodicAlarm_CallbackFunctionPointer = Callback;
}

void TimeService_startPeriodicAlarm_CMockIgnoreArg_seconds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TimeService_startPeriodicAlarm_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_seconds = 1;
}

void TimeService_startPeriodicAlarm_CMockIgnoreArg_callback(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_startPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TimeService_startPeriodicAlarm_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_callback = 1;
}

void TimeService_stopPeriodicAlarm(int handle)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TimeService_stopPeriodicAlarm);
  cmock_call_instance = (CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TimeService_stopPeriodicAlarm_CallInstance);
  Mock.TimeService_stopPeriodicAlarm_CallInstance = CMock_Guts_MemNext(Mock.TimeService_stopPeriodicAlarm_CallInstance);
  if (Mock.TimeService_stopPeriodicAlarm_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.TimeService_stopPeriodicAlarm_CallbackBool &&
      Mock.TimeService_stopPeriodicAlarm_CallbackFunctionPointer != NULL)
  {
    Mock.TimeService_stopPeriodicAlarm_CallbackFunctionPointer(handle, Mock.TimeService_stopPeriodicAlarm_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_handle)
  {
    UNITY_SET_DETAILS(CMockString_TimeService_stopPeriodicAlarm,CMockString_handle);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_handle, handle, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.TimeService_stopPeriodicAlarm_CallbackFunctionPointer != NULL)
  {
    Mock.TimeService_stopPeriodicAlarm_CallbackFunctionPointer(handle, Mock.TimeService_stopPeriodicAlarm_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_TimeService_stopPeriodicAlarm(CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE* cmock_call_instance, int handle);
void CMockExpectParameters_TimeService_stopPeriodicAlarm(CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE* cmock_call_instance, int handle)
{
  cmock_call_instance->Expected_handle = handle;
  cmock_call_instance->IgnoreArg_handle = 0;
}

void TimeService_stopPeriodicAlarm_CMockIgnore(void)
{
  Mock.TimeService_stopPeriodicAlarm_IgnoreBool = (char)1;
}

void TimeService_stopPeriodicAlarm_CMockStopIgnore(void)
{
  Mock.TimeService_stopPeriodicAlarm_IgnoreBool = (char)0;
}

void TimeService_stopPeriodicAlarm_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE));
  CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TimeService_stopPeriodicAlarm_CallInstance = CMock_Guts_MemChain(Mock.TimeService_stopPeriodicAlarm_CallInstance, cmock_guts_index);
  Mock.TimeService_stopPeriodicAlarm_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void TimeService_stopPeriodicAlarm_CMockExpect(UNITY_LINE_TYPE cmock_line, int handle)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE));
  CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TimeService_stopPeriodicAlarm_CallInstance = CMock_Guts_MemChain(Mock.TimeService_stopPeriodicAlarm_CallInstance, cmock_guts_index);
  Mock.TimeService_stopPeriodicAlarm_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_TimeService_stopPeriodicAlarm(cmock_call_instance, handle);
}

void TimeService_stopPeriodicAlarm_AddCallback(CMOCK_TimeService_stopPeriodicAlarm_CALLBACK Callback)
{
  Mock.TimeService_stopPeriodicAlarm_IgnoreBool = (char)0;
  Mock.TimeService_stopPeriodicAlarm_CallbackBool = (char)1;
  Mock.TimeService_stopPeriodicAlarm_CallbackFunctionPointer = Callback;
}

void TimeService_stopPeriodicAlarm_Stub(CMOCK_TimeService_stopPeriodicAlarm_CALLBACK Callback)
{
  Mock.TimeService_stopPeriodicAlarm_IgnoreBool = (char)0;
  Mock.TimeService_stopPeriodicAlarm_CallbackBool = (char)0;
  Mock.TimeService_stopPeriodicAlarm_CallbackFunctionPointer = Callback;
}

void TimeService_stopPeriodicAlarm_CMockIgnoreArg_handle(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimeService_stopPeriodicAlarm_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TimeService_stopPeriodicAlarm_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_handle = 1;
}

